version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecocycle-backend
    ports:
      - "2341:2341" 
    volumes:
      - ./backend:/app  
      - ./backend/data.db:/app/data.db  
    environment:
      - FLASK_ENV=development

volumes:
  postgres_data:
