FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 2341

CMD ["python", "db.py"]  # Make sure this points to the correct file if it's named differently
